# Generated by Django 5.2.4 on 2025-07-27 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('username', models.CharField(blank=True, max_length=50, null=True)),
                ('expire_date', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'managed': True,
            },
        ),
    ]
